version: '2.4'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ../backend.Dockerfile
    ports:
      - 4000:4000

  frontend:
    build:
      context: ./frontend
      dockerfile: ../frontend.Dockerfile
    ports:
      - 8080:8080

  postgres:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=real_world_dev
